# Generated by Django 5.0 on 2024-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='program/')),
                ('bahasa', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=50)),
                ('uraian', models.TextField()),
            ],
        ),
    ]
