# Generated by Django 5.0 on 2024-03-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_dataproject_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='github',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
